# Generated by Django 3.2.18 on 2023-03-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='form',
            name='urls',
        ),
        migrations.AddField(
            model_name='form',
            name='urls',
            field=models.ManyToManyField(to='projects.FormURL'),
        ),
    ]
