# Generated by Django 3.2.18 on 2023-03-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20230313_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='daily_emails',
            field=models.ManyToManyField(blank=True, related_name='daily_emails', to='projects.Email'),
        ),
        migrations.AlterField(
            model_name='project',
            name='daily_forms',
            field=models.ManyToManyField(blank=True, related_name='daily_forms', to='projects.Form'),
        ),
        migrations.AlterField(
            model_name='project',
            name='daily_notifications',
            field=models.ManyToManyField(blank=True, related_name='daily_notifications', to='projects.Notification'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modes',
            field=models.ManyToManyField(blank=True, to='projects.Mode'),
        ),
        migrations.AlterField(
            model_name='project',
            name='purposes',
            field=models.ManyToManyField(blank=True, to='projects.Purpose'),
        ),
    ]
