# Generated by Django 3.2.18 on 2023-03-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20230320_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='add_list',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='user_email_mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
