# Generated by Django 3.2.18 on 2023-03-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20230322_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='label',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
