# Generated by Django 3.2.18 on 2023-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20230322_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.AlterField(
            model_name='project',
            name='modes',
            field=models.ManyToManyField(blank=True, related_name='modes', to='projects.Mode'),
        ),
    ]
