# Generated by Django 3.2.18 on 2023-04-05 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20230324_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='purposes',
        ),
    ]
