# Generated by Django 3.2.18 on 2023-04-05 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20230405_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='What order to display this Purpose within the project.', null=True, verbose_name='Order')),
                ('project', models.ForeignKey(help_text='Purpose belongs to this projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
                ('purpose', models.ForeignKey(help_text='Purpose belongs to this projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.purpose', verbose_name='Purpose')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, help_text='What order to display this Mode within the project.', null=True, verbose_name='Order')),
                ('mode', models.ForeignKey(help_text='Mode belongs to this projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.mode', verbose_name='Mode')),
                ('project', models.ForeignKey(help_text='Mode belongs to this projet', null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='modes',
            field=models.ManyToManyField(blank=True, related_name='modes', through='projects.ProjectMode', to='projects.Mode'),
        ),
        migrations.AddField(
            model_name='project',
            name='purposes',
            field=models.ManyToManyField(blank=True, through='projects.ProjectPurpose', to='projects.Purpose'),
        ),
    ]
