# Generated by Django 3.2.18 on 2023-04-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20230405_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmode',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='projectpurpose',
            options={'ordering': ('order',)},
        ),
    ]
