# Generated by Django 3.2.18 on 2023-04-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20230405_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='template_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
