# Generated by Django 3.2.18 on 2023-04-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_email_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='notification_messages', to='projects.EmailMessages'),
        ),
    ]
