# Generated by Django 3.2.18 on 2023-10-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_date',
        ),
    ]
