# Generated by Django 3.2.18 on 2023-10-10 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20230413_2234'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='projects',
            new_name='project',
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'email', 'project')},
        ),
    ]
