# Generated by Django 3.2.18 on 2023-10-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20230413_2234'),
        ('userprofile', '0002_auto_20231010_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='projects.project'),
        ),
    ]
